POST http://localhost:3001/api/notes
content-type: application/json

{
    "content": "testing mongoose with REST Client",
    "important": true
}

### 
DELETE http://localhost:3001/api/notes/64fd95468c4345c229fd5041

###
PUT http://localhost:3001/api/notes/64fd95238c4345c229fd5041
content-type: application/json

{
    "content": "Testing Mongoose with REST Client"
}