POST http://localhost:3001/api/notes
content-type: application/json

{
    "content": "testing mongoose with REST Client",
    "important": true
}

### 
DELETE http://localhost:3001/api/notes/650303784014ec83c90225ac

###
PUT http://localhost:3001/api/notes/650303bd4014ec83c90225ba
content-type: application/json

{
    "content": "aaaaa"
}